project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "xvdefrance/index.qmd"
    - "rwcsquads2023/index.qmd"

description-meta: "Julien Migozzi's personal website."

website:
  title: "Julien Migozzi"
  description: "Website of Julien Migozzi"
  search: false
  navbar:
    left:
      - text: "Julien Migozzi, PhD"
        href: /
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: aof.qmd
        text: Atlas of Finance
      - href: media.qmd
        text: Media
      - href: cv/index.qmd
        text: CV
    title: false
  page-footer:
    center: "Made with [quarto](https://quarto.org)"
  google-analytics:
    tracking-id: "G-DM8RWDZ57L"
    storage: none
    anonymize-ip: true

execute:
  freeze: auto

format:
  html:
    theme:
      - custom2.scss
    include-in-header: fontawesome.html
    fontsize: 1rem