---
title: ""
page-layout: article
format:
  html:
    css: language-toggle.css
---

<div class="language-toggle">
  <a href="about.html" class="language-btn">ENGLISH</a>
  <a href="about_fr.html" class="language-btn language-btn-active">FRENCH</a>
</div>


### Recherche

A la croisée de la géographie, des études urbaines et de la sociologie économique, mes recherches portent sur les technologies numériques, la finance, et les villes, afin de comprendre comment le capitalisme numérique affecte le fonctionnement des marchés et l'évolution des inégalités socio-spatiales. Je mobilise des méthodes mixtes, associant l'enquête ethnographique à l'analyse spatiale et aux sciences sociales computationnelles.

Mon premier axe de recherche analyse comment le capitalisme numérique transforme les marchés immobiliers et influence les processus de stratification sociale et de ségrégation urbaine. J'étudie notamment l'industrie de la PropTech (PropertyTechnology), soit l'ensemble des technologiques numériques appliqué au secteur de l'immobilier.

La géographie de la finance constitue mon deuxième champ de recherche. J'étudie nnotamment rôle du numérique (FinTech) et du capital-risque (*private equity*) dans la formation des écosystemes et marchés financiers aux échelles internationales, régionales et urbaines.

L’Afrique du Sud et la ville du Cap, où je mène des recherches approfondies depuis 2015, constituent mon principal cas d'étude et terrain d'enquête.

Je suis co-auteur de l'[Atlas de la Finance](https://atlasoffinance.com/), publié aux Presses Universitaires de Yale et traduit en français aux [Éditions du Seuil](https://www.seuil.com/ouvrage/atlas-de-la-finance-paul-lepic/9782021598308). 

 
### Parcours

Je suis ancien élève de l'École Normale Supérieure de Lyon et agrégé de géographie. J'ai réalisé mon doctorat à l'Université Grenoble Alpes et à l'UMR Géographie-cités (Paris). Ma thèse a reçu deux prix nationaux : le [Grand Prix de Thése sur la ville ](https://www.urbanisme-puca.gouv.fr/prix-de-these-sur-la-ville-2021-a2141.html?lang=en) et le [Prix de Thèse](https://www.cnfg.fr/vie-du-comite/prix-dethese-du-cnfg/) du Comité National Français de Géographie.

A l'University d'Oxford, j'ai été lauréat de la Postdoctoral Research Fellowship décernée par la [Urban Studies Foundation](https://www.urbanstudiesfoundation.org/) (2022-2026), et postdoctorant en Finance et Géographie sur le projet ERC  [Cities in Global Financial Networks](https://cordis.europa.eu/project/id/681337) (2021-2022). Auparavant, j'ai occupé les fonctions d'Agrégé-Préparateur et d'ATER au Département de Géographie de l'École Normale Supérieure (2017-2021). J'ai été  chercheur invité à l'African Centre for Cities (Université du Cap, 2016 et 2023) ainsi qu'au Département de Sociologie de UC Berkeley (2024-2025).