---
title: ""
---

## Research interests

My research interests lie at the intersection of economic geography, urban studies, and economic sociology.

I investigate how digital technologies transform financial and housing markets, reshape urban housing markets in the Global South, and renew mechanisms of segregation and inequalities, with a focus on South Africa.

I am particularly interested in understanding how the sectors of PropTech and FinTech impact cities and markets from a social, political and economical perspective.

Methodologically, my work combines qualitative and ethnographic research with computational tools, spatial analysis and mapping, mostly with R and QGIS.

My current project is funded by the [Urban Studies Foundation](https://www.urbanstudiesfoundation.org/) and focuses on real estate platforms in South Africa.

I occasionally [write](https://jmigozzi.github.io/posts.html#category=Rugby) and talk about the geography and sociology of rugby.


## Dissertation


My [PhD dissertation](https://www.theses.fr/en/2020GRALH007), "*A city to sell. Digitalization and financialization of the housing market in Cape Town: stratification & segregation in the emerging global city*", was awarded two national prizes: 

- the 2021 [Doctoral Prize in Urban Studies](http://www.urbanisme-puca.gouv.fr/prix-de-these-sur-la-ville-2021-a2141.html) by the PUCA-APERAU-Caisse des Dépôts;

- the 2021 [Dissertation Award in Geography](https://www.cnfg.fr/vie-du-comite/prix-de-these-du-cnfg/) by the French National Committee of Geography (CNFG). 

The thesis also received a Special mention of the jury for the 2021 [Humanities and social sciences PSL Dissertation Prize](https://psl.eu/en/news/winners-2021-humanities-and-social-sciences-shs-psl-dissertation-prize).


In this work, I demonstrated how the digitalization of the real estate industry structured around the implementation of credit scoring and the rise of real estate platforms reshaped the functioning of the housing market, enabling a selective financialization of housing across the mortgage market and the private rental sector. These market reconfigurations have renewed mechanisms and patterns of social stratification and urban segregation in Cape Town, a post-apartheid and emerging city of the Global South.

To investigate the housing market, I conducted 18 months of fieldwork among the real estate industry, from real estate agents to mortgage lenders, from corporate investors to ordinary households. I used expert interviews and ethnographic methods. In parallel, In order to analyze how the spatial dynamics of price and credit influence the evolution of income-based and racial segregation, I sourced raw deeds data to build a database of 900,000 geolocated sales, covering the metro area from 1984 to 2017, and digitally reconstructed the zoning of apartheid. This database was cross-analysed with longitudinal census data. I used open source tools such as R and QGIS to perform computational and spatial analysis.


## Education and Affiliations

Most of my curriculum took place in France, and included research visits in South Africa and study abroad programs at the Victoria University of Wellington in New Zealand. 

I earned my MA from the [Ecole Normale Supérieure de Lyon](https://www.ens-lyon.fr/en/), and my PhD from the [University of Grenoble Alpes](https://www.univ-grenoble-alpes.fr/english/). From 2017 to 2021, I was a Lecturer in the Department of Geography at [the Ecole Normale Supérieure](https://www.ens.psl.eu/en) in Paris.

At Oxford University, I previously worked on the ERC project "[Cities in Global Financial Network](https://www.citynet21.org/)" as a Research Associate in Finance and Geography. Our team authored the first Atlas of Finance, forthcoming at Yale University Press in 2024.

I am Associate Member of the [St Peter's College](https://www.spc.ox.ac.uk/), and a regular Visiting Scholar at the [African Center for Cities](https://www.africancentreforcities.net/) at the University of Cape Town.I remain a Research Associate at the Research Centre [Géographie-cités](https://geographie-cites.cnrs.fr/en/geographie-cites/), where I was a doctoral candidate. Since 2023, I'm an early career representative at the [FinGeo Network](https://www.fingeo.net/).
