---
title: "Research"
listing:
  id: main-listing
  contents: 
    - ville_et_numerique
    - housing_inequity
    - financialization_housing_sa
    - who_sells_whom
    - national_parks_market
    - new_caledonia
    - rugby_schools
    - rugby_sa
    
    - apartheid_algorithm
    - india_fintech
    - india_ma
    - metropolitics
    - rental_platforms
  type: default
  categories: true
  image-align: left
  sort: "date desc"
---

## Publications

:::{#main-listing}
:::

## Public scholarship


- *Diagonal*, 2022,  "[An interview with Julien Migozzi, recipient of the dissertation award](https://www.openedition.org/23454)", Issue 215.
- Migozzi, J., 2019, "[When real estate financialization filters people out](https://ideas4development.org/en/financialization-real-estate-filter/)", ideas4development.
- Migozzi, J., 2019, "[L’Afrique du Sud : le rugby, un sport de blancs ?](https://www.lhistoire.fr/afrique-du-sud-le-rugby-un-sport-de-blancs%C2%A0)", *L’Histoire*, n°8.

## Media

- Interview for *Libération*, "[Coupe du monde de rugby 2023 : en Afrique du Sud, les rugbymen noirs gagnent du terrain](https://www.liberation.fr/sports/rugby/coupe-du-monde-de-rugby-2023-en-afrique-du-sud-les-rugbymen-noirs-gagnent-du-terrain-20230908_OZM4MCGIEFE7NFWWOTBFPSYSIY/)".


## Dissertation

My [PhD dissertation](https://www.theses.fr/en/2020GRALH007) was awarded two national prizes: 

- the 2021 [Doctoral Prize in Urban Studies](http://www.urbanisme-puca.gouv.fr/prix-de-these-sur-la-ville-2021-a2141.html) by the PUCA-APERAU-Caisse des Dépôts;

- the 2021 [Dissertation Award in Geography](https://www.cnfg.fr/vie-du-comite/prix-de-these-du-cnfg/) by the French National Committee of Geography (CNFG). 

The thesis also received a Special mention of the jury for the 2021 [Humanities and social sciences PSL Dissertation Prize](https://psl.eu/en/news/winners-2021-humanities-and-social-sciences-shs-psl-dissertation-prize).

In this work, I demonstrated how the digitalization of the real estate industry structured around the implementation of credit scoring and the rise of real estate platforms reshaped the functioning of the housing market, enabling a selective financialization of housing across the mortgage market and the private rental sector. These market reconfigurations  have renewed mechanisms and patterns of social stratification and urban segregation in Cape Town, a post-apartheid and emerging city of the Global South.

To investigate the housing market, I conducted 18 months of fieldwork among the real estate industry, from real estate agents to mortgage lenders, from  corporate investors to ordinary households. I used expert interviews and ethnographic methods. In parallel,  In order to analyze how the spatial dynamics of price and credit influence the evolution of income-based and racial segregation, I sourced raw deeds data to build a database of 900,000 geolocated sales, covering the metro area from 1984 to 2017, and digitally reconstructed the zoning of apartheid. This database was cross-analysed with longitudinal census data. I used open source tools such as R and QGIS to perform computational and spatial analysis.

